### ISSUE TITLE
Scrape public data from a website and to store it as JSON file

### ISSUE THREAD

**Issue by FedericoElles** [FedericoElles/codemill#1]
**Tech:** #node #request #cheerio #geocoding

**Details:** https://github.com/FedericoElles/codemill/tree/master/waldorf_kindergarten_de

**Comment by FedericoElles** [comment]
**Codemill** codemill$44

**Comment by semanser** [comment]
@FedericoElles so it need list of German cities first, right?

**Comment by FedericoElles** [comment]
@semanser Just checked: Yes, no lat,lng are accepted by the search input. Here is a list of all major cities: http://www.citymayors.com/gratis/german_topcities.html

**Comment by FedericoElles** [comment]
@BenZalekta has been assigned to this task.

**Comment by FedericoElles** [comment]
@BenZalekta has been unassigned from this task.

**Comment by FedericoElles** [comment]
@jniebuhr has been assigned to this task.

**Comment by jniebuhr** [comment]
Single file is quite hard, i guess we need at least a package.json :)
